### PR TITLE
Do not dereference nil pointer in case of non-matching filenames.

### PR DESCRIPTION
**Pull request by keltia**
I did the previous PR because of that nil-pointer dereference.

### CODE REVIEW

**Comment by codebrane** [comment]
thanks for that. Can you explain what it does? The changed lines 59-61 don't appear to have functionality

**Comment by keltia** [comment]
According to Alistair Young on Wed, Mar 30, 2016 at 01:16:32AM -0700:

> thanks for that. Can you explain what it does? The changed lines 59-61 don't appear to have functionality

The visit() func is called for every file found.  If the filename does not match, the array returned is nil which means that matching[1] will make the program panic.

After my change, the non-matching filename is just ignored.

## 

Ollivier ROBERT -=- FreeBSD: The Power to Serve! -=- roberto@keltia.net
In memoriam to Ondine, our 2nd child: http://ondine.keltia.net/

**Comment by codebrane** [comment]
according to Files changed, the only commit will carry on to octopressFilenameWithoutExtension := matches[1] regardless of matches? the braces at 60,61 are empty

**Comment by keltia** [comment]
Oops, PR updated.

**Comment by keltia** [comment]
According to Alistair Young on Wed, Mar 30, 2016 at 01:37:57AM -0700:

> according to Files changed, the only commit will carry on to octopressFilenameWithoutExtension := matches[1] regardless of matches? the braces at 60,61 are empty

Are saying I may have forgot to put the needed "return nil" somewhere?

#oops

You're right...

## 

Ollivier ROBERT -=- FreeBSD: The Power to Serve! -=- roberto@keltia.net
In memoriam to Ondine, our 2nd child: http://ondine.keltia.net/

**Comment by codebrane** [comment]
good stuff, thanks for the PR

**Pull request merged**
