### PR TITLE
Fix error on open + stderr

### PR DESCRIPTION
**Pull request by keltia**
Some small cleanups.

### CODE REVIEW

**Comment by codebrane** [comment]
can you check line 78 in Files Changed? it continues to write to file if hugoFileError != nil and 208-210 don't look right. It's saying the buffer is too small if isPrefix. Should that be up around line 78?

**Comment by keltia** [comment]
I've fixed line 78 sorry.  Line 208 is right because you have "return nil" in both inside and outside the if().

**Comment by codebrane** [comment]
not sure about 208 and 211. if isPrefix doesn't appear to do anything but the method returns nil?

**Comment by keltia** [comment]
According to Alistair Young on Wed, Mar 30, 2016 at 07:36:57AM -0700:

> not sure about 208 and 211. if isPrefix doesn't appear to do anything but the method returns nil?

I don't really care, I'm just saying that you will return nil anyway :)

## 

Ollivier ROBERT -=- FreeBSD: The Power to Serve! -=- roberto@keltia.net
In memoriam to Ondine, our 2nd child: http://ondine.keltia.net/

**Pull request merged**
